### ISSUE TITLE
People view UI 수정

### ISSUE THREAD

**Issue by gbmksquare** [letswiftconf/LetSwift#114]
- [x] 헤더 full width, 3:4 비율
- [x] iPad / Mac 한 줄에 5명
- [x] organization 1줄에 표시
<img width="172" alt="image" src="https://user-images.githubusercontent.com/3669202/100018384-baeead00-2e1f-11eb-8820-7214020e272b.png">

**Comment by 1Consumption** [comment]
organization을 한줄로 표시하면 organization 이름이 너무 긴 경우 organizati... 이렇게 될 것 같아서 일부러 여러줄로 설정 했습니다.
대안을 다음과 같이 생각해봤습니다.

1. 생략 되어도 괜찮으니 한줄로 표시
2. organization이름이 너무 긴 경우 fontsize를 줄임. -> 일관성을 해칠 것 같습니다.
3. 그대로 유지

어떤 것이 나을까요? 혹시 다른 생각이 있다면 알려주시면 감사하겠습니다.

**Comment by gbmksquare** [comment]
Staff 정보 보니 다행히 엄청 길지는 않을거 같고요, 혹시라도 잘리면 전반적으로 폰트를 작게하죠!

**Comment by gbmksquare** [comment]
#119
